### PR TITLE
Added email verification module

### PR DESCRIPTION
**Pull request by MadhavBahl**
npm install the required dependencies.
See INSTRUCTIONS.md for more info.
merge the pull request and attack this code to your server main.js 💯

### CODE REVIEW

**Comment by MohitChattlani** [comment]
That means we can use react along with hbs?

**Comment by MadhavBahl** [comment]
You can render hbs. But there is no need to, i just used hbs because i am
habitual of doing so, basic html rendering would work very fine ✌

**Comment by MohitChattlani** [comment]
You have made a separate app. Here I wanted you to integrate with my Project which uses react. 
React uses virtual dom and thus will not be able to integrate with this code.
If you can do so please do otherwise I will try to integrate myself.

**Comment by MadhavBahl** [comment]
I dont use react, so i wont be able to do so.....
If you want i can see docs and try to integrate it.

**Comment by MadhavBahl** [comment]
But if i do so it will take time.. atleast a week.

**Comment by MohitChattlani** [comment]
No need bro, I will look at your code and try to integrate it.

**Comment by MadhavBahl** [comment]
Ok great 👌

**Comment by MadhavBahl** [comment]
By the way, can you merge this code please 😄

**Pull request closed without merging**
